Repository sprint-part3-team10/tenten, pull requests merged in 2024-04, with the labels that each got.

#1 [Chore] stylelint classname 카멜케이스 rule 추가
  .stylelintrc.json
Labels: 🧩Component

#23 [Setting] tsconfig @경로 수정, 아이콘 파일 추가, 폰트 적용
  public/icons/clock.svg
  public/icons/close.svg
  public/icons/location.svg
  public/icons/logo.svg
  public/icons/phone.svg
  src/app/globals.scss
  src/app/layout.tsx
  tsconfig.json
Labels: ⚙️ Setting

#26 [Feat] Card 컴포넌트 구현
  package-lock.json
  package.json
  public/icons/clock_gray.svg
  public/icons/location_gray.svg
  public/images/cherry.png
  src/app/page.module.scss
  src/app/page.tsx
  src/components/Card.module.scss
  src/components/Card.tsx
  src/lib/format.ts
  src/lib/formatDate.ts
Labels: 🧩Component

#24 [Feat] 로그인, 회원가입 페이지 초기 구성 및 Input, Button, TypeSelector 컴포넌트 생성
  package-lock.json
  package.json
  public/icons/checked.svg
  public/icons/circleChecked.svg
  public/icons/circleNotChecked.svg
  public/icons/eyeoff.svg
  public/icons/eyeon.svg
  src/app/signin/page.module.scss
  src/app/signin/page.tsx
  src/app/signup/page.module.scss
  src/app/signup/page.tsx
  src/components/TypeSelector.module.scss
  src/components/TypeSelector.tsx
  src/components/common/Button.module.scss
  src/components/common/Button.tsx
  src/components/common/button.tsx
  src/components/common/input/Input.module.scss
  src/components/common/input/Input.tsx
  src/constants/signRegEx.ts
Labels: 🧩Component, 📰 Page

#27 [Feat] 공용 Dropdown 컴포넌트 구현
  .eslintrc.json
  public/icons/dropdown-down.svg
  public/icons/dropdown-up.svg
  src/components/common/Dropdown.module.scss
  src/components/common/Dropdown.tsx
  src/constants/dropdownList.ts
  src/hooks/useOutsideClick.tsx
Labels: 🧩Component

#32 [Feat] MyProfile, Label, NoList, ApplyTable 컴포넌트 구현
  package-lock.json
  package.json
  public/icons/approve.svg
  public/icons/labelClose.svg
  public/icons/reject.svg
  src/app/mypage/page.tsx
  src/components/applylist/ApplyStatus.tsx
  src/components/applylist/ApplyTable.module.scss
  src/components/applylist/ApplyTable.tsx
  src/components/applylist/Label.module.scss
  src/components/applylist/Label.tsx
  src/components/applylist/NoList.module.scss
  src/components/applylist/NoList.tsx
  src/components/common/Alarms.module.scss
  src/components/common/Alarms.tsx
  src/components/myProfile/MyProfile.module.scss
  src/constants/constant.ts
  src/styles/mixins/_responsive.scss
Labels: 🧩Component

#29 [Design] Layout 구현
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.module.scss
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.module.scss
  src/app/(auth)/signup/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/page.module.scss
  src/app/(main)/mypage/page.tsx
  src/app/(main)/page.module.scss
  src/app/(main)/page.tsx
  src/app/page.module.scss
  src/components/layout/Footer.tsx
  src/hooks/useHideComponent.tsx
Labels: 🪟 Layout

#36 [Feat] Modal 제작
  public/icons/modalCheck.svg
  public/icons/modalWarning.svg
  src/app/(main)/layout.tsx
  src/components/common/Button.module.scss
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalPortal.tsx
Labels: 🧩Component

#38 [Feat] 반응형 mobile일 때 close 버튼 구현
  public/icons/alarmsNotRead.svg
  public/icons/alarmsRead.svg
  src/app/(main)/mypage/page.module.scss
  src/app/(main)/mypage/page.tsx
  src/components/common/AlarmSet.module.scss
  src/components/common/AlarmSet.tsx
  src/components/common/Alarms.module.scss
  src/components/common/Alarms.tsx
Labels: 🧩Component

#40 [Feat] Header 컴포넌트 구현 및 eslint rule 변경
  .eslintrc.json
  public/icons/search.svg
  src/app/(main)/layout.tsx
  src/app/(main)/page.module.scss
  src/components/SearchBar.module.scss
  src/components/SearchBar.tsx
  src/components/common/Dropdown.tsx
  src/components/layout/Header.module.scss
  src/components/layout/header.tsx
Labels: 🧩Component, 🪟 Layout, ⚙️ Setting

#46 [Fix] Card 눌렀을 때 URL 변경 및 util 함수 파일 변경
  src/app/(main)/page.tsx
  src/components/Card.tsx
  src/lib/caculate.ts
  src/lib/format.ts
  src/lib/formatWage.ts
Labels: 🧩Component

#45 [Feat] Toast 컴포넌트
  public/icons/completed.png
  public/icons/warning.svg
  src/components/common/toast/Toast.module.scss
  src/components/common/toast/Toast.tsx
  src/hooks/useToast.tsx
Labels: 🧩Component

#48 [Fixed]: isStatic prop 삭제, placeholder, onChange prop 추가, 작동 조건 추가 및 변경
  src/components/common/input/Input.tsx
Labels: 🪲 Bug, 🧩Component

#49 [Feat] Location box, FilterPopover 컴포넌트 구현
  src/components/applylist/Label.module.scss
  src/components/applylist/Label.tsx
  src/components/filterPopover/Filter.module.scss
  src/components/filterPopover/FilterButton.tsx
  src/components/filterPopover/FilterPopover.tsx
  src/components/filterPopover/LocationBox.module.scss
  src/components/filterPopover/LocationBox.tsx
Labels: 🧩Component

#47 [Feat] Pagination 컴포넌트 구현
  public/icons/leftArrow.svg
  public/icons/rightArrow.svg
  src/app/(main)/page.tsx
  src/components/layout/Header.tsx
  src/components/pagination/Pagination.module.scss
  src/components/pagination/Pagination.tsx
  src/hooks/usePagination.tsx
  src/hooks/useTest.tsx
Labels: 🧩Component

#52 [Fixed]: Input 컴포넌트 inputType 변경 및 API 작업 내용 관련 props 추가, 변경
  src/api/postLogin.ts
  src/api/postUser.ts
  src/app/(auth)/signup/page.tsx
  src/components/common/Button.tsx
  src/components/common/input/Input.module.scss
  src/components/common/input/Input.tsx
  src/components/common/toast/Toast.tsx
  src/hooks/useToast.tsx
Labels: 🪲 Bug, 🧩Component, 📫 API

#53 [Feat] mypage(알바의 내 프로필 페이지) & ApplyTable component userType에 따른 로직 구현 & pagination 수정
  src/api/getProfileData.tsx
  src/api/getShopApply.tsx
  src/api/getUserApply.tsx
  src/app/(main)/mypage/page.module.scss
  src/app/(main)/mypage/page.tsx
  src/app/(main)/myprofile/page.module.scss
  src/app/(main)/myprofile/page.tsx
  src/components/applylist/ApplyTable.module.scss
  src/components/applylist/ApplyTable.tsx
  src/components/applylist/Label.module.scss
  src/components/applylist/Label.tsx
  src/components/applylist/NoList.module.scss
  src/components/applylist/NoList.tsx
  src/components/myProfile/MyProfile.module.scss
  src/components/myProfile/MyProfile.tsx
  src/components/pagination/Pagination.tsx
Labels: 🪲 Bug, 🧩Component, 📰 Page, 📫 API

#60 [Feat] 로그인, 회원가입 API 연동 및 POST 기능 수행, 페이지 이동 동작 초기 구현
  src/api/postLogin.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/page.tsx
Labels: 📰 Page, 📫 API

#54 [Feat] MyProfile 등록 페이지 구현
  src/api/api.ts
  src/app/(main)/myprofile/page.tsx
  src/app/(main)/myprofile/register/page.module.scss
  src/app/(main)/myprofile/register/page.tsx
  src/app/(main)/page.tsx
  src/components/applylist/NoList.tsx
  src/components/common/BackSpaceButton.tsx
  src/components/common/Dropdown.module.scss
  src/components/common/Dropdown.tsx
  src/components/common/TextArea.module.scss
  src/components/common/TextArea.tsx
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/Modal.tsx
  src/components/layout/Header.module.scss
  src/constants/regEx.ts
Labels: 🧩Component, 📰 Page

#63 [Fix & Feat] DatePicker 공용 컴포넌트 수정 및 RFC3339 변환 유틸함수 구현
  src/components/common/Datepicker.tsx
  src/components/common/Dropdown.module.scss
  src/lib/convertToRFC3339.ts
Labels: 🧩Component, 📰 Page

#67 [Fixed] 회원가입 페이지 Toast 및 Error 관련 동작 수정
  src/api/postLogin.ts
  src/api/postUser.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/hooks/useToast.tsx
  src/lib/setCookie.ts
Labels: 🪲 Bug, 📰 Page, 📫 API

#65 [Feat] 가게상세페이지
  src/api/getNoticeData.ts
  src/api/getProfileData.ts
  src/api/getShopApply.ts
  src/api/getUserApply.ts
  src/api/getUserApply.tsx
  src/api/postApplication.ts
  src/api/putAlarmStatus.ts
  src/app/(main)/myprofile/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.module.scss
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/ApplyEventContainer.tsx
  src/components/applylist/ApplyTable.module.scss
  src/components/applylist/ApplyTable.tsx
  src/components/common/modal/Modal.tsx
Labels: 📰 Page

#66 [Feat] 메인페이지 하단 CardList 컴포넌트(페이지네이션, 상세필터) 구현
  next.config.mjs
  src/api/getCardData.ts
  src/app/(main)/layout.tsx
  src/app/(main)/page.module.scss
  src/app/(main)/page.tsx
  src/components/Card.tsx
  src/components/RecentViews.tsx
  src/components/card/Card.module.scss
  src/components/card/Card.tsx
  src/components/card/CardList.module.scss
  src/components/card/CardList.tsx
  src/components/common/Datepicker.tsx
  src/components/common/WageComparisonBadge.module.scss
  src/components/common/WageComparisonBadge.tsx
  src/components/filterPopover/Filter.module.scss
  src/components/filterPopover/FilterButton.tsx
  src/components/filterPopover/FilterPopover.tsx
  src/components/filterPopover/LocationBox.module.scss
  src/components/filterPopover/LocationBox.tsx
  src/components/pagination/Pagination.tsx
  src/constants/dropdownList.ts
  src/hooks/usePagination.tsx
  src/types/types.ts
Labels: 🧩Component, 📰 Page

#71 [Feat] 로그아웃 기능 구현 및 Header 적용, userType에 따른 Header Button 구성 방식 조건 추가, 일부 파일 경로 수정
  src/components/common/LogoutButton.tsx
  src/components/layout/Header.tsx
  src/components/store/MyShopNotices.tsx
  src/lib/checkLogin.ts
  src/lib/deleteCookie.ts
Labels: 🪲 Bug, 🧩Component, 🪟 Layout

#75 [Feat] Header의 검색바(SearchBar) 기능 구현 및 Input의 '원' 단위가 붙는 조건 변경
  src/components/SearchBar.tsx
  src/components/common/input/Input.tsx
Labels: 🧩Component, 🪟 Layout

#73 [Feat] 내 가게 정보 등록 및 수정 페이지 기능 구현
  public/icons/camera.svg
  src/api/createPresignedUrl.ts
  src/api/postMyShop.ts
  src/api/putMyShop.ts
  src/app/(main)/myprofile/register/page.tsx
  src/app/(main)/myshop/page.tsx
  src/app/(main)/myshop/register/page.module.scss
  src/app/(main)/myshop/register/page.tsx
  src/components/common/Dropdown.module.scss
  src/components/common/Dropdown.tsx
  src/components/store/MyShopRegister.module.scss
  src/components/store/MyShopRegister.tsx
  src/lib/getCookie.ts
  src/lib/setShopIdCookie.ts
  src/types/interface.ts
Labels: 🧩Component, 📰 Page, 📫 API

#76 [Feat] 알람 구현
  package-lock.json
  public/icons/cancel.svg
  src/api/getAlarms.ts
  src/api/getShopApply.ts
  src/api/getUserApply.ts
  src/api/putAlarmRead.ts
  src/api/putAlarmStatus.ts
  src/app/(main)/myprofile/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/applylist/ApplyTable.tsx
  src/components/card/Card.tsx
  src/components/common/AlarmSet.tsx
  src/components/common/Alarms.tsx
  src/components/common/alarms/AlarmContainer.module.scss
  src/components/common/alarms/AlarmContainer.tsx
  src/components/common/alarms/AlarmIcon.module.scss
  src/components/common/alarms/AlarmIcon.tsx
  src/components/common/alarms/AlarmSet.tsx
  src/components/common/alarms/Alarms.module.scss
  src/components/common/alarms/Alarms.tsx
  src/components/myProfile/MyProfile.tsx
  src/constants/constant.ts
  src/lib/caculate.ts
  src/lib/getCookies.ts
Labels: 🧩Component, 📰 Page, 📫 API

#79 [Feat] 내 프로필 등록 및 수정 기능 구현
  src/api/putMyProfile.ts
  src/app/(main)/myprofile/register/page.module.scss
  src/app/(main)/myprofile/register/page.tsx
  src/components/myProfile/MyProfileRegister.module.scss
  src/components/myProfile/MyProfileRegister.tsx
  src/types/interface.ts
Labels: 🧩Component, 📰 Page, 📫 API

#77 [Feat] 알바공고상세페이지
  src/app/(main)/myshop/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/ApplyEventContainer.tsx
  src/components/store/ShopNoticeInfoBox.tsx
Labels: 🪲 Bug, 📰 Page

#78 [Feat] 메인페이지에 맞춤 공고를 위한 CustomCardList, Carousel 컴포넌트, 검색페이지를 위한 SearchCardList 컴포넌트 구현
  src/api/getCardData.ts
  src/app/(main)/page.module.scss
  src/app/(main)/page.tsx
  src/app/(main)/search/page.tsx
  src/components/SearchBar.module.scss
  src/components/card/Card.module.scss
  src/components/card/Card.tsx
  src/components/card/CardList.module.scss
  src/components/card/CardList.tsx
  src/components/card/Carousel.module.scss
  src/components/card/Carousel.tsx
  src/components/card/CustomCardList.module.scss
  src/components/card/CustomCardList.tsx
  src/components/card/SearchCardList.tsx
  src/components/pagination/Pagination.tsx
  src/components/store/ShopNoticeInfoBox.tsx
  src/constants/constant.ts
  src/styles/base/_reset.scss
Labels: 🧩Component, 📰 Page

#81 [Fixed] 모든 cookie를 설정할 수 있는 setCookies 파일 생성 및 적용, employer 로그인 조건 추가, 로그아웃 시 modal을 통한 확인 기능 추가, Input에서 Enter 동작 개선
  src/api/postLogin.ts
  src/api/postMyShop.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/common/LogoutButton.tsx
  src/components/common/input/Input.tsx
  src/lib/checkLogin.ts
  src/lib/setCookie.ts
  src/lib/setCookies.ts
  src/lib/setShopIdCookie.ts
Labels: 🪲 Bug, 🧩Component, 📫 API

#84 [Feat] CardList 필터 초기값 변경, Spinner 컴포넌트 구현
  src/app/(main)/layout.tsx
  src/app/(main)/search/page.tsx
  src/components/Spinner.module.scss
  src/components/Spinner.tsx
  src/components/card/CardList.module.scss
  src/components/card/CardList.tsx
  src/components/card/CustomCardList.tsx
  src/lib/convertToRFC3339.ts
Labels: 🧩Component, 🪟 Layout

#87 [Feat] 모달 기능 추가, 경로 접근 동작 추가 등
  .eslintrc.json
  src/api/api.ts
  src/api/getNoticeData.ts
  src/api/getProfileData.ts
  src/api/getShop.ts
  src/api/getShopNotices.ts
  src/api/postApplication.ts
  src/api/putAlarmStatus.ts
  src/api/putApplication.ts
  src/app/(main)/myprofile/layout.tsx
  src/app/(main)/myshop/layout.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/error.module.scss
  src/app/(main)/shops/[shopId]/notices/[noticeId]/error.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/loading.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/app/not-found.tsx
  src/app/notFound.scss
  src/components/ApplyEventContainer.module.scss
  src/components/ApplyEventContainer.tsx
  src/components/CancelApplyEventContainer.module.scss
  src/components/CancelApplyEventContainer.tsx
  src/components/common/modal/Modal.tsx
Labels: 🪲 Bug, 🪟 Layout, 📫 API

#89 [Fixed] input 내 eyeIcon이 tap 키보드 입력에 영향을 받지 않도록 수정, 로그인 및 회원가입 Toast 유지 시간 단축 및 Warning 문제 해결, 로그아웃 modal의 버튼 위치 변경, TypeSelector 리펙토링
  public/icons/circleChecked.svg
  src/app/(auth)/signin/page.module.scss
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.module.scss
  src/app/(auth)/signup/page.tsx
  src/components/TypeSelector.module.scss
  src/components/TypeSelector.tsx
  src/components/common/LogoutButton.tsx
  src/components/common/input/Input.tsx
  src/components/common/toast/Toast.tsx
  src/components/layout/Header.tsx
  src/hooks/useToast.tsx
Labels: 🪲 Bug, 🧩Component

#90 [Fixed] 공고 화면에서 logout 시 메인 화면으로 넘어가지 않는 문제 수정, 로그인 비밀번호 error 판단 case 수정
  src/app/(auth)/signin/page.module.scss
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.module.scss
  src/components/SearchBar.tsx
  src/components/common/LogoutButton.tsx
  src/components/layout/Footer.tsx
Labels: 🪲 Bug

#92 [Fix] 등록 및 수정 페이지 수정 및 pink 테마 적용
  public/icons/clock.svg
  public/icons/location.svg
  public/icons/logo.svg
  public/icons/modalCheck.svg
  public/icons/modalWarning.svg
  public/icons/phone.svg
  src/api/createPresignedUrl.ts
  src/app/(main)/myprofile/register/page.module.scss
  src/app/(main)/myprofile/register/page.tsx
  src/app/(main)/myshop/register/notice/page.module.scss
  src/app/(main)/myshop/register/page.module.scss
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.module.scss
  src/app/notFound.scss
  src/components/Spinner.module.scss
  src/components/TypeSelector.module.scss
  src/components/applylist/ApplyTable.module.scss
  src/components/applylist/Label.module.scss
  src/components/card/CardList.module.scss
  src/components/card/CustomCardList.module.scss
  src/components/common/Button.module.scss
  src/components/common/Datepicker.tsx
  src/components/common/Dropdown.module.scss
  src/components/common/WageComparisonBadge.module.scss
  src/components/common/alarms/AlarmContainer.module.scss
  src/components/common/alarms/AlarmIcon.module.scss
  src/components/filterPopover/Filter.module.scss
  src/components/filterPopover/LocationBox.module.scss
  src/components/myProfile/MyProfile.module.scss
  src/components/myProfile/MyProfileRegister.module.scss
  src/components/myProfile/MyProfileRegister.tsx
  src/components/pagination/Pagination.module.scss
  src/components/store/MyNoticeRegister.module.scss
  src/components/store/MyNoticeRegister.tsx
  src/components/store/MyShopRegister.tsx
  src/components/store/ShopNoticeInfoBox.module.scss
  src/constants/dropdownList.ts
  src/styles/constants/_color.scss
Labels: 🪲 Bug

#93 [Fix, Refactor] Carousel, CustomCardList, Card 보수 작업
  next.config.mjs
  src/api/getCardData.ts
  src/components/card/Card.module.scss
  src/components/card/Card.tsx
  src/components/card/Carousel.module.scss
  src/components/card/Carousel.tsx
  src/components/card/CustomCardList.module.scss
  src/components/card/CustomCardList.tsx
  src/types/types.ts
Labels: 🪲 Bug, 🧩Component

#95 [Refactor] 코드 내 eslint, stylelint 에러 해결을 위한 refactoring 작업 및 추가 디자인 작업
  public/icons/circleChecked.svg
  src/app/(auth)/signin/page.module.scss
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.module.scss
  src/app/(auth)/signup/page.tsx
  src/components/TypeSelector.module.scss
  src/components/common/Button.module.scss
  src/components/common/LogoutButton.tsx
  src/components/common/toast/Toast.module.scss
  src/hooks/useToast.tsx
  src/lib/checkLogin.ts
Labels: 🪲 Bug, 🧩Component

#94 [Fix&Refactor] 알람&테이블 리팩토링
  .eslintrc.json
  src/api/getAlarms.ts
  src/api/getShopApply.ts
  src/api/getUserApply.ts
  src/app/(main)/myprofile/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.module.scss
  src/components/applyList/ApplyTable.module.scss
  src/components/applyList/ApplyTable.tsx
  src/components/applyList/Label.module.scss
  src/components/applyList/Label.tsx
  src/components/applyList/NoList.module.scss
  src/components/applyList/NoList.tsx
  src/components/common/alarms/AlarmContainer.module.scss
  src/components/common/alarms/AlarmContainer.tsx
  src/components/common/alarms/AlarmIcon.module.scss
  src/components/common/alarms/AlarmIcon.tsx
  src/components/common/alarms/AlarmSet.tsx
  src/components/layout/Header.tsx
  src/components/myProfile/MyProfile.module.scss
  src/components/myProfile/MyProfile.tsx
  src/types/types.ts
Labels: 🪲 Bug, 🧩Component

#96 [Chore, Fix] 에러 제거, eslint rules 추가
  .eslintrc.json
  public/icons/wageArrowRed.svg
  src/api/getProfileData.ts
  src/components/card/Card.module.scss
  src/components/card/CardList.tsx
  src/constants/constant.ts
Labels: 🪲 Bug, ⚙️ Setting

#98 [Fix, Refactor] 전체 공고 개수 표시, 추가 에러 제거
  src/components/SearchBar.tsx
  src/components/TypeSelector.tsx
  src/components/card/CardList.module.scss
  src/components/card/CardList.tsx
  src/components/common/LogoutButton.tsx
Labels: 🪲 Bug, 🧩Component

#100 [Fix] 등록 및 수정 페이지 타입오류 해결 및 반응형 수정
  src/app/(main)/myprofile/register/page.module.scss
  src/app/(main)/myshop/register/notice/page.module.scss
  src/app/(main)/myshop/register/page.module.scss
  src/components/common/Datepicker.tsx
  src/components/myProfile/MyProfileRegister.module.scss
  src/components/myProfile/MyProfileRegister.tsx
  src/components/store/MyNoticeRegister.module.scss
  src/components/store/MyNoticeRegister.tsx
  src/components/store/MyShopRegister.module.scss
  src/components/store/MyShopRegister.tsx
Labels: 🪲 Bug

#97 [Refactor] 공고상세 줄바꿈 해제, 인상율뱃지 생략 해제 등
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/RecentViews.module.scss
  src/components/RecentViews.tsx
  src/components/common/WageComparisonBadge.module.scss
  src/components/common/WageComparisonBadge.tsx
  src/components/common/modal/Modal.tsx
  src/components/store/ShopNoticeInfoBox.module.scss
  src/components/store/ShopNoticeInfoBox.tsx
  test.http
Labels: 🪲 Bug, 📄 Documentation, 🧩Component

#101 [Fixed] number 타입에서 키보드 위아래로 수치 조작되던 문제 수정, Logo 수정
  public/icons/logo.png
  public/icons/logo.svg
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/common/input/Input.tsx
  src/components/layout/Header.tsx
Labels: 🪲 Bug, 🧩Component

#102 [Fix] 빌드 관련 타입 수정, eslint 룰 추가
  .eslintrc.json
  package.json
  src/api/getCardData.ts
  src/api/getProfileData.ts
  src/api/getShop.ts
  src/app/(main)/error.module.scss
  src/app/(main)/error.tsx
  src/components/card/CustomCardList.tsx
  src/components/common/Datepicker.tsx
  src/components/common/toast/Toast.tsx
  src/components/myProfile/MyProfile.tsx
  src/lib/getCookie.ts
Labels: 🪲 Bug, 📫 API, ⚙️ Setting

#103 [Docs, Fixed] README 파일 1차(초안) 작성, customCardList 내에 사용된 Date() 삭제
  README.md
  src/components/card/CustomCardList.tsx
Labels: 📄 Documentation

#104 [Fix] 가게 종류 보이도록 수정
  src/api/getCardData.ts
  src/app/(main)/myshop/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/store/ShopNoticeInfoBox.tsx
Labels: 🪲 Bug, 🧩Component, 📰 Page

#105 [Docs, Fixed] README 파일 1차 작성 완료, favicon 추가 및 title 수정
  README.md
  public/icons/favicon.ico
  src/app/(auth)/layout.tsx
  src/app/(main)/layout.tsx
  src/app/layout.tsx
Labels: 📄 Documentation
