Repository sprint-part3-team10/tenten, pull requests merged in 2024-05, with the labels that each got.

#108 [Design, Refactor] 헤더 버튼 hover 동작 추가, 검색바 반응형 동작 시 width 관련 수정, modal 버튼 크기 조정
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.module.scss
  src/components/SearchBar.module.scss
  src/components/common/Button.module.scss
  src/components/layout/Header.module.scss
Labels: 🧩Component

#109 [Feat] 공고페이지 공유 버튼 제작
  package-lock.json
  package.json
  public/icons/share.svg
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.module.scss
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/app/layout.tsx
  src/components/share/Share.module.scss
  src/components/share/Share.tsx
Labels: 🧩Component

#110 [Refactor] 알람, 테이블 UI 수정 & opengraph image 설정
  src/app/layout.tsx
  src/components/applyList/ApplyTable.module.scss
  src/components/common/alarms/AlarmContainer.module.scss
Labels: 🪟 Layout

#112 [Fix] Kakao 식별자 배포 오류 수정
  src/components/share/Share.tsx
Labels: 🪲 Bug

#115 [Refactor] 사장 상세주소 추가, 토스트 z-index 수정
  src/app/(main)/myshop/page.tsx
  src/components/common/toast/Toast.module.scss
  src/components/store/ShopNoticeInfoBox.module.scss
  src/components/store/ShopNoticeInfoBox.tsx
Labels: 🧩Component

#116 [Fix] 배포 타입 오류 수정
  README.md
  src/app/(main)/myshop/page.tsx
  src/app/(main)/shops/[shopId]/notices/[noticeId]/page.tsx
  src/components/common/toast/Toast.module.scss
  src/components/store/ShopNoticeInfoBox.module.scss
  src/components/store/ShopNoticeInfoBox.tsx
Labels: 🪲 Bug
